apiVersion: v1
data:
  ALCHEMY_BSC_MAINNET_URL: aHR0cHM6Ly9ibmItbWFpbm5ldC5nLmFsY2hlbXkuY29tL3YyL1dzWVRQVjF2Tkk4N3FXZ1NoeUFfRg==
  ALCHEMY_BSC_TESTNET_URL: aHR0cHM6Ly9ibmItdGVzdG5ldC5nLmFsY2hlbXkuY29tL3YyL1dzWVRQVjF2Tkk4N3FXZ1NoeUFfRg==
  BSC_CHAIN_ID: NTY=
  ENCRYPTION_MASTER_KEY: YzI2ODBiNjYwNTNlMGRiNWNjOWZmNjJmMzVlNWMzOTg5ODQ0YTZkNDEyYzZiM2FmZjNiNjM2YTk1MDI2N2I1Yg==
  FRONTEND_ORIGIN: aHR0cHM6Ly90cmFkZXIuaG9sZGVyZm9yZ2UuaW8=
  JWT_ACCESS_SECRET: bDYwMlcyY2orQ1d1SEZJb1p6U3kwZFVGNVh2bVAzMWZNUWxnR1B4dUVmcw==
  JWT_REFRESH_SECRET: UE5aWHBaTFZFN0R6MkpHMllyUVRYWkJNVnZXcGZlQzlDZ0JQMk9GS1RPdw==
  MONGODB_DNS_SERVERS: OC44LjguOCw4LjguNC40
  MONGODB_URI: bW9uZ29kYitzcnY6Ly9jaGFuZHJhc2hla2hhcmdhd2RhMjAwMF9kYl91c2VyOmNGbHR3UllZWWE5Yk1rbnlAZGV4Ym90MS5uYm15ZHh4Lm1vbmdvZGIubmV0Lw==
  NODE_ENV: cHJvZHVjdGlvbg==
  PANCAKE_V2_ROUTER: MHgxMEVENDNDNzE4NzE0ZWI2M2Q1YUE1N0I3OEI1NDcwNEUyNTYwMjRF
  PANCAKE_V3_QUOTER: MHhCMDQ4QmJjMUVlNmI3MzNGRmZDRmI5ZTlDZUY3Mzc1NTE4ZTI1OTk3
  PANCAKE_V3_ROUTER: MHgxM2Y0RUE4M0QwYmQ0MEU3NUM4MjIyMjU1YmM4NTVhOTc0NTY4RGQ0
  PORT: NDAwMA==
  REDIS_URL: IHJlZGlzOi8vMTcyLjE3LjAuMTo2Mzc5
  TELEGRAM_BOT_TOKEN: MDAwMDAwMDAwMDpyZXBsYWNlX3dpdGhfeW91cl9ib3RfdG9rZW4=
  UNISWAP_V2_ROUTER: MHg0NzUyYmE1REJjMjNmNDREODc4MjYyNzZCRjZGZDZiMUMzNzJhRDI0
  VITE_ALCHEMY_BSC_URL: aHR0cHM6Ly9ibmItbWFpbm5ldC5nLmFsY2hlbXkuY29tL3YyL1dzWVRQVjF2Tkk4N3FXZ1NoeUFfRg==
  VITE_API_BASE_URL: aHR0cHM6Ly90cmFkZXIuaG9sZGVyZm9yZ2UuaW8vYXBp
  VITE_DEV_BACKEND_URL: aHR0cDovL2xvY2FsaG9zdDo0MDAw
  VITE_SOCKET_URL: aHR0cHM6Ly90cmFkZXIuaG9sZGVyZm9yZ2UuaW8=
  VITE_WALLETCONNECT_PROJECT_ID: ZTUwMjcxZTkyNjM4M2NhMTE4NmQ5MjU1YzQ2ODFlN2M=
  WBNB_ADDRESS: MHhiYjRDZEI5Q0JkMzZCMDFiRDFjQmFFQkYyRGUwOGQ5MTczYmMwOTVj
kind: Secret
metadata:
  creationTimestamp: "2026-07-24T05:48:24Z"
  name: dexbot-secret
  namespace: dexbot
  resourceVersion: "901"
  uid: 7b4c1b2f-e10a-430f-8d70-5a5469b5623d
type: Opaque
