apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: trader-ingress
  namespace: dexbot
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod

spec:
  ingressClassName: nginx

  tls:
    - hosts:
        - trader.holderforge.io
      secretName: trader-holderforge-io-tls

  rules:
    - host: trader.holderforge.io
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: dex-frontend
                port:
                  number: 80
