name: Deploy To VPS

on:
  workflow_run:
    workflows:
      - Build Pipeline
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest

    steps:
      - name: Deploy to Contabo VPS
        uses: appleboy/ssh-action@v1.2.2
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.PORT }}
          timeout: 60s
          command_timeout: 20m
          debug: true

          script: |
            set -e

            cd /root/otp/apps/DEX_BOT

            echo "${{ secrets.GHCR_TOKEN }}" | docker login ghcr.io \
              -u "${{ secrets.GHCR_USERNAME }}" \
              --password-stdin

            docker compose pull

            docker compose up -d --remove-orphans

            docker image prune -af

            docker ps
